#pragma once
#include "toolbox/datastructure/implicit_treap/implicit_treap.hpp"
#include "toolbox/datastructure/sparse_table/sparse_table.hpp"
#include "toolbox/datastructure/treap/treap.hpp"
#include "toolbox/datastructure/unionfind/unionfind.hpp"
#include "toolbox/datastructure/unionfind_weighted/unionfind_weighted.hpp"
#include "toolbox/datastructure/wavelet_tree/wavelet_tree.hpp"
// #include "segment_tree"
// #include "fenwick_tree"
// #include "lazy_segment_tree"
// #include "persistent_segment_tree"
// #include "splay_tree"
// #include "treap"
// #include "link_cut_tree"
// #include "heavy_light_decomposition"
